apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy2
  labels:
    app: example-app2
    test: test
  annotations:
    fluxcd.io/tag.podinfod: semver:0.0.*
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: example-app2
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app2
    spec:
      containers:
      - name: example-app2
        image: joshdwalker/umbriel
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets/
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: secret-volume
        secret:
          secretName: mysecret
      - name: config-volume
        configMap:
          name: example-config #name of our configmap object
